blog/urls.py
from django.urls import path, include
from . import views
from . import APIviews
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title="Swagger Docs")
app_name = 'blog'
urlpatterns=[
    path("", views.homepage, name="homepage"),
    path("post/<post_slug>", views.blog_post, name="post"),
    path("category/<slug>", views.category_posts, name="category_posts"),
    path("contact-me/", views.visitor_message, name="message"),
    path("login/", views.login, name="login"),
    path("about-me/", views.about_me, name="aboutme"),
    path("post/JSON/", APIviews.PostView.as_view(), name="posts_json"),
    path("post/<slug>/JSON/", APIviews.PostDetail.as_view(), name="post_detail"),
    path("category/JSON/", APIviews.CategoryView.as_view(), name="categories_json"),
    path("category/<slug>/JSON/", APIviews.CategoryPostsView.as_view(), name="category_posts_json"),
    path("docs/", schema_view, name="api_docs"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include('blog.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime



class Category(models.Model):
    name = models.CharField(max_length=100)
    category_slug = models.CharField(max_length=200, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Tutorial(models.Model):
    slug = models.CharField(max_length=200, default="1")
    title = models.CharField(max_length=200)
    content = models.TextField()
    min_read = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    comments = models.IntegerField(default=0)
    img_url = models.CharField(max_length=250 ,null=True)

    def commented(self):
        self.comments += 1
        self.save(update_fields=['comments'])

    def __str__(self):
        return self.title

class Message(models.Model):
    author = models.CharField(max_length=60, default="visitor")
    email = models.CharField(max_length=120)
    body = models.TextField()
    created_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.author

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    tutorial = models.ForeignKey(Tutorial, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

blog/forms.py
from django import forms

class MessageForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        required=False,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Name not required"
        })
    )

    email = forms.CharField(
        required=False,
         widget=forms.EmailInput(attrs={
            "class": "form-control",
            "placeholder": "Mail not required"
        })
    )

    body = forms.CharField(
        widget=forms.Textarea(attrs={
            "class": "form-control",
            "placeholder": "Write your message :)"
        })
    )


class CommentForm(forms.Form):
    comment = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control comment",
            "placeholder": "Leave your comment!"
        })
    )

blog/views.py
from django.core.paginator import Paginator
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .models import Category, Tutorial, Message, Comment
from .forms import MessageForm, CommentForm
from ratelimit.decorators import ratelimit


def homepage(request):
    '''
    blog home page with the latest 6 posts and categories
    Args:
        object: request
    Returns:
        list: latest posts
        list: blog categories
    '''
    categories = Category.objects.all()
    posts = Tutorial.objects.all()

    paginator = Paginator(posts, settings.POST_PER_PAGE)
    page = request.GET.get('page', 1)
    posts = paginator.get_page(page)

    context = {
        'posts': posts,
        'categories': categories}
    return render(request, 'home.html', context=context)


def blog_post(request, post_slug):
    '''
    get post by id
    Args:
        object: request
        int: post id
    Returns:
        object: post
    '''
    categories = Category.objects.all()
    try:
        tutorial = Tutorial.objects.get(slug=post_slug)
    except Tutorial.DoesNotExist:
        raise Http404
    # comments related to post
    post_comments = Comment.objects.filter(tutorial__pk=tutorial.pk).all()
    form = CommentForm()
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('blog:login')

        form = CommentForm(request.POST)
        if form.is_valid():
            print(request.user)
            comment = Comment(
                content=form.cleaned_data["comment"],
                tutorial=tutorial,
                user=request.user
            )
            comment.save()
            tutorial.commented()
            return redirect('blog:post', post_id=tutorial.pk)
    context = {'tutorial': tutorial,
               'categories': categories,
               'form': form,
               'comments': post_comments
               }
    return render(request, 'post.html', context=context)


def category_posts(request, slug):
    '''
    get posts related to category
    Args:
        object: request
        string: category slug
    Returns:
        list: posts in the category
        list: all categories
        int: number of posts in that category
    '''
    try:
        category = Category.objects.get(category_slug=slug)
    except Category.DoesNotExist:
        raise Http404
    related_tutorials = Tutorial.objects.filter(category=category).all()
    categories = Category.objects.all()
    tut_count = len(related_tutorials)
    context = {'latest_items': related_tutorials,
               'categories': categories,
               'category': category,
               'tut_count': tut_count}
    return render(request, 'category_posts.html', context=context)


@ratelimit(key='ip', rate='100/h', block=True)
def visitor_message(request):
    '''
    visitors messages
    Args:
        object: request
    Returns:
        object: message form
    '''
    form = MessageForm()
    if request.method == 'POST':
        # save message
        form = MessageForm(request.POST)
        if form.is_valid():
            message = Message(
                author=form.cleaned_data["author"],
                email=form.cleaned_data["email"],
                body=form.cleaned_data["body"]
            )
            message.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Thanks! message delivered successfully')
            return redirect("blog:homepage")

    return render(request, 'contact_me.html', context={"form": form})


# Login endpoint
def login(request):
    return render(request, 'login.html')


# about me page
def about_me(request):
    return render(request, 'who_am_i.html')

blog/templates/categories_block.html
<h4 class="text-center category">Categories</h4>
<section class="categry-tags">
  <ul class="tags">
    {% for category in categories %}
    <li><a href="{% url 'blog:category_posts' category.category_slug%}" class="badge badge-dark"> {{category.name}}</a></li>
    {% endfor %}
  </ul>

</section>

blog/templates/category_posts.html
{% extends 'base.html' %}
{% block title %}Hossam El-Hwary{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="row">
        <h2 class="text-center">{{category.name}} POSTS ({{tut_count}})</h2>
        {% include 'post_card.html' %}
      </div>
    </div>

    <div class="col-md-4">
      {% include 'categories_block.html' %}

    </div>
        
        

</div>


{% endblock %}

blog/templates/contact_me.html
{% extends 'base.html' %}
{% block title %}Hossam El-Hwary{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <div class="row">
        <h2 class="text-center">Leave Your message</h2>
        <form action="{% url 'blog:message' %}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            <div class="form-group">
                    {{ form.author }}
                </div>
                <div class="form-group">
                    <label>Type your mail to contact you</label>
                        {{ form.email }}
                    </div>
                <div class="form-group">
                    {{ form.body }}
                </div>
                <div style="text-align: center;">
                <button type="submit" class="btn btn-success">Submit</button>
                </div>
        </form>


      </div>
    </div>

    <div class="col-md-2"></div>
      

    </div>
        
        

</div>


{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}
{% block title %}Hossam El-Hwary{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <h2 class="text-center">POSTS</h2>
                {% include 'post_card.html' %}
            </div>
        </div>

        <div class="col-md-4">
            {% include 'categories_block.html' %}

        </div>
    </div>

    <div class="row align-items-center justify-content-center">
        {% include "pagination/pagination.html" with page=posts %}
    </div>

{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% block title %}Hossam El-Hwary{% endblock %}


{% block content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        
        <a href="{% url 'social:begin' 'github' %}" class="btn btn-block btn-social btn-github">
            <span class="fa fa-github"></span> Sign in with Github
        </a>
          
        <a href="{% url 'social:begin' 'facebook'%}" class="btn btn-block btn-social btn-facebook">
            <span class="fa fa-facebook"></span> Sign in with Facebook
        </a>
     
    </div>
    <div class="col-md-3"></div>

</div>
</div>
{% endblock %}

blog/templates/pagination/pagination.html
{% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% if page.has_previous %}
            <li><a href="?page={{ page.previous_page_number }}">&laquo;</a></li>
            <li><a href="?page={{ page.previous_page_number }}">previous</a>
            </li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        <li class="active"><span>Page {{ page.number }} of {{ page.paginator.num_pages }}.<span class="sr-only">(current)</span></span></li>

        {% if page.has_next %}
            <li><a href="?page={{ page.next_page_number }}">next</a></li>

            <li><a href="?page={{ page.paginator.num_pages }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>

        {% endif %}
    </ul>
{% endif %}

blog/templates/post.html
{% extends 'base.html' %}
{% block title %}Hossam El-Hwary{% endblock %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <h2 class="text-center">{{tutorial.title}}</h2>
            <p class="card-text text-center post-info">
                <small class="text-muted">Created at: {{tutorial.updated_at|date:"D d M Y"}}</small>
                <small class="text-muted">Last updated: {{tutorial.updated_at|naturaltime}}</small>
                <small class="text-muted">{{tutorial.min_read}} min read</small>
                <span class="text-muted">Category{{tutorial.category.all|pluralize}}: 
                    {% for category in tutorial.category.all%}
                     {{ category.name }}
                     {%endfor%}
                    
                </span>
                
              </p>
            <section>
                {{tutorial.content | safe}}
            </section>
            </div>
    </div>

    <div class="col-md-4">
        {% include 'categories_block.html' %}

    </div>

    
    <div class="row">
        <div class="col-md-12">
            <h2>Leave your comment!</h2>
            <section class="comment-form">
            <form accept="{%url 'blog:post' tutorial.pk%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group comment">
                    {{form.comment}}
                </div>
                {% if user.is_authenticated %}
                <button type="submit" class="btn btn-success">Comment</button>
                {%else%}
                    <strong><a href="{%url 'blog:login'%}">Login</a> <span> to comment</span></strong>
                {%endif%}
            </form>
        </section>
        <hr>

            {%for comment in comments%}
                <div class="comment-block">
                    <img class="float-left img-circle comment-img" src="{% static 'imgs/user.png' %}" alt="avatar">
                    <div class="media-body">
                      <h5 class="custom-heading comment-name">{{comment.user.username}}</h5>
                      <p class="card-text">
                            <small class="text-muted">{{comment.created_at|naturaltime}}</small>
                        </p>
                      <p>{{comment.content}}</p>
                    </div>
                  </div>

        {%endfor%}
        </div>
    </div>

</div>
{% endblock%}

blog/templates/post_card.html
{% for aricle in posts %}
    <div class="card mb-3 post-card">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="{{ aricle.img_url }}" class="card-img img-responsive post-img" alt="...">
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <a href="{% url 'blog:post' aricle.slug %}"><h3
                            class="card-title post-title">{{ aricle.title }}</h3></a>
                    <p class="card-text">
                        <small class="text-muted">Last updated {{ aricle.updated_at|date:"D d M Y" }}</small>
                        <small class="text-muted">{{ aricle.min_read }} min read</small>
                        <a href="#"> <span
                                class="text-muted">{{ aricle.comments }} comment{{ aricle.comments|pluralize }}</span>
                        </a>
                    </p>
                    <p class="card-text">
                        {{ aricle.content|slice:":200"|safe }}...
                    </p>
                    <a class="more-link" href="{% url 'blog:post' aricle.slug %}"></a>
                </div>

            </div>
        </div>
    </div>

{% endfor %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/github-activity.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}" />
	<link rel="shortcut icon" href="{%  static 'imgs/favicon.ico' %}">

  
    <link rel="stylesheet" href="{% static 'css/octicons.min.css' %}">


    <title>{% block title%}{% endblock %}</title>
</head>
<body>



    <main class="container">
        <div class="row nav-margin">
        <div class="col-md-12">
            <nav class="navbar navbar-default">
                    <div class="container-fluid">
                      <!-- Brand and toggle get grouped for better mobile display -->
                      <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                      </div>
                  
                      <!-- Collect the nav links, forms, and other content for toggling -->
                      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav nav-list-edit">
                            <li><a class="navbar-brand nav-edit" href="{% url 'blog:homepage'  %}">Blog posts</a></li> 
                            <li><a class="navbar-brand nav-edit" href="{% url 'blog:aboutme'%}">Who am I?</a></li>  
                            <li><a class="navbar-brand nav-edit" href="{%url 'blog:message'%}">Contact me</a></li>
                            <li><a class="navbar-brand nav-edit" href="{%url 'blog:api_docs'%}">API</a></li>
                            {%if user.is_authenticated%}
                            <li><a class="navbar-brand nav-edit" href="{% url 'logout'%}">Logout</a></li>
                            {%else%}
                            <li><a class="navbar-brand nav-edit" href="{% url 'blog:login'%}">Login</a></li>
                            {%endif%}
                        </ul>
                      </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                  </nav>
    
        </div>
        
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}

                    {% if message.tags == "info"%}
                    <div class="isa_info">
                        <i class="fa fa-info-circle"></i>
                        {{message}}
                    </div>
                    {%elif message.tags == "success"%}
                    <div class="isa_success">
                        <i class="fa fa-check"></i>
                        {{message}}
                   </div>
                    {% elif message.tags == "warning"%}
                    <div class="isa_warning">
                        <i class="fa fa-warning"></i>
                        {{message}}
                   </div>
                    {%elif message.tags == "error"%}
                    <div class="isa_error">
                        <i class="fa fa-times-circle"></i>
                        {{message}}
                     </div>
                     {% endif %}
                    
                    {% endfor %}
                </ul>
                {% endif %}

            </div>
            <div class="col-md-3"></div>
          </div>
        </div>
        {% block content %}

        {% endblock %}

    </main>
    
    <!-- Footer -->
<footer class="page-footer font-small">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://github.com/hussamEL-Hwary"> Hossam</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

    <script src="{% static 'tinymce/js/prism.js' %}"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.2/mustache.min.js"></script>
    <script type="text/javascript" src="{% static 'js/github-activity.js' %}"></script>

  
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
     <script>
      GitHubActivity.feed({ username: "hussamEL-Hwary", selector: "#feed" });
    </script>
</body>
</html>